index.refresh_interval defaults to 1s, so data inserted will be visible to search after min 1s

diff --git a/.github/workflows/skap.yaml b/.github/workflows/skap.yaml
--- a/.github/workflows/skap.yaml
+++ b/.github/workflows/skap.yaml
@@ -26,10 +26,11 @@ jobs:
         run: |
           cd kafka-connect-http
           mvn -B test
-      - name: kafka-connect-http integration-test
-        run: |
-          cd kafka-connect-http
-          mvn -B integration-test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'kafka-connect-http/target/surefire-reports/TEST-*.xml'
 
   package:
     runs-on: ubuntu-latest
